### ISSUE TITLE
Rename repo to denso if possible

### ISSUE THREAD

**Issue by 130s** [start-jsk/denso#13]
Discussed [here](https://github.com/shadow-robot/denso/issues/1).

**Comment by 130s** [comment]
[This case is settled](https://github.com/shadow-robot/denso/issues/1); we'll rename our packages.

For descriptions, we'll also pay attention to #14.

@wyasuda fyi.

**Comment by gavanderhoorn** [comment]
Just curious: are you going to go with an all capitals package name? Seeing as the ROS naming guidelines explicitly allow only the use of lowercase alphanumerics (and underscores)?

**Comment by 130s** [comment]
@gavanderhoorn Nope, as I said I'll apply all-capital rule to the package description only (I'm aware of ROS package naming convention and those where package name start with capital shed so many annoying warnings).

**Comment by 130s** [comment]
Fix via 817a7a8. #14 is done as well.
