### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by k-okada** [start-jsk/denso#15]
open_industrial_ros_controllers depends on pr2_controller_manager

and

vs060_moveit_config depends on moveit_ros_visualization

**Comment by 130s** [comment]
Fixed via af601cc for `vs060_moveit_config`. 

`pr2_controller_manager` has already been listed for [open_controller_interface](https://github.com/start-jsk/open_industrial_ros_controllers/blob/6911d51821527232a3e90a3748db4fe18f7ffccd/open_controllers_interface/package.xml) (`open_industrial_ros_controllers` is merely a meta-package). So while I'm still not sure why some people see error like below, I'm closing this ticket:

```
[realtime_loop-4] process has died [pid 2420, exit code -11, cmd /opt/ros/hydro/lib/denso_controller/main -x /opt/ros/hydro/share/vs060/model/vs060A1_AV6_NNN_NNN.urdf -s -d __name:=realtime_loop __log:=/home/yasuda/.ros/log/bc05772c-63a2-11e3-8a42-180373c50ff4/realtime_loop-4.log].
log file: /home/yasuda/.ros/log/bc05772c-63a2-11e3-8a42-180373c50ff4/realtime_loop-4*.log
[ERROR] [1386903666.825366325]: Not using the PR2 controller manager
```

**Comment by gavanderhoorn** [comment]
@130s: -11 is a segfault (as you probably know). Not sure whether a missing dependency can cause those.

**Comment by 130s** [comment]
@wyasuda 

With [this issue](https://github.com/start-jsk/open_industrial_ros_controllers/issues/14) fixed, do you still see the issue I cited [above](https://github.com/start-jsk/densowave/issues/15#issuecomment-30500008), which is actually what you saw? As @gavanderhoorn pointed out, the error looks like segfault and might not have anything to do with dependency by itself.

**Comment by k-okada** [comment]
@gavanderhoorn  Segfault should be fixed in issue https://github.com/start-jsk/open_industrial_ros_controllers/issues/14, please check with latest version

**Comment by 130s** [comment]
@k-okada @wyasuda Great! Then I'll release a new patch version 0.2.6
