### ISSUE TITLE
(Question on answers) Can the DENSO VS060 package run the DENSO VE026A arm?

### ISSUE THREAD

**Issue by 130s** [start-jsk/denso#18]
http://answers.ros.org/question/117346/can-the-denso-vs060-package-run-the-denso-ve026a-arm/
fyi @garaemon @k-okada

**Comment by garaemon** [comment]
Hmm...

As @k-okada  said, If VE026A supports BCap, it should work.

But we need to update denso controller a little bit because it has several hard-coding parameters such as the number of actuators.
It's not so difficult to fix

https://github.com/start-jsk/denso/issues/19

**Comment by mcross8** [comment]
Thanks for the reply! The VE026A does run in slave mode, however it requires a serial connection rather than an Ethernet. 

For example the VE026A is connected as a serial device (ttyUSB0 on my Ubuntu box). Does the current Denso controller seek serial devices or just Ethernet connected devices?

**Comment by k-okada** [comment]
Currently denso package only supports ethernet, I filed  a new ticket #20,  @mcross8, if you have example code for serial connection, please provide us, to improve development.

**Comment by mcross8** [comment]
I do not know the state of this code, nor am I familiar enough with ROS to try to implement it myself:

https://code.google.com/p/hiveground-ros-pkg/source/browse/controllers/denso/

**Comment by 130s** [comment]
I guess enough good conversation happened so now I close this. @mcross8 if you have more to say please feel free to add / reopen and continue.
