### ISSUE TITLE
Component diagram for denso packages (along with IREX design)

### ISSUE THREAD

**Issue by 130s** [start-jsk/denso#32]
I'm trying to understand the current design:
<img src="https://docs.google.com/drawings/d/1-AcMxG_kE2yUP-11OwdutZuTR2hOF0DUjF5nnitHhNs/pub?w=909&amp;h=634">

**Comment by k-okada** [comment]
seems good, 
- DensoController, OpenController and b-cap is not a different process
- denso controllers talk to moveit or robot state publisher
