### ISSUE TITLE
Separate denso_controller/main.cpp into .h and .cpp

### ISSUE THREAD

**Issue by 130s** [start-jsk/denso#33]
Currently [main.cpp](https://github.com/start-jsk/denso/blob/a535489d0480aef6fd972af35437a856d3782af4/denso_controller/src/main.cpp) is all-in-one. For maintenance purpose it's better to be splitted.
I have [started working](https://github.com/130s/denso/commit/093cdfe31a26bef8a5a96d01a677fc54ba85e3ec) in my own repo.

**Comment by garaemon** [comment]
the reason why all the code is implemented in one cpp file is maintenance purpose.
we don't need to maintain two files.

I thought that there would be no class which inherits denso controller and I didn't need to expose the 
definition of the class.

**Comment by 130s** [comment]
> I thought that there would be no class which inherits denso controller and I didn't need to expose the
> definition of the class.

Oh, okay, I thought that was because of the rush before the exhibition. So long as this statement stands, I agree that we can keep `main.cpp` as it is (I shoul've asked in advance).

(But still, it's not a generally accepted concept isn't it, to keep header, impl and main in a single .cpp file for whatever reasons?)
