### ISSUE TITLE
ros-hydro-denso-launch does not depend on  ros-hydro-denso

### ISSUE THREAD

**Issue by mmurooka** [start-jsk/denso#41]
I'm very light user of start-jsk/denso.
I tried the following command and got the error, that vs060 is not found.

> sudo aptitude install ros-hydro-denso-launch
> roslaunch denso_launch denso_vs060_moveit_demo_simulation.launch 
> ...
> ResourceNotFound: vs060
> ROS path [0]=/opt/ros/hydro/share/ros
> ROS path [1]=/home/murooka/ros/hydro/src
> ROS path [2]=/opt/ros/hydro/share
> ROS path [3]=/opt/ros/hydro/stacks

After I install ros-hydro-denso, the previous launch file worked.

It seems that ros-hydro-denso-launch does not depend on ros-hydro-denso.
It this correct?

> $ sudo aptitude show ros-hydro-denso-launch
> パッケージ: ros-hydro-denso-launch  
> 新規: はい
> 状態: インストール済み
> 自動的にインストールされた: いいえ
> バージョン: 0.2.7-0precise-20140717-1602-+0000
> 優先度: 特別
> セクション: misc
> メンテナ: Ryohei Ueda ueda@jsk.t.u-tokyo.ac.jp
> アーキテクチャ: amd64
> 展開サイズ: 77.8 k
> 依存: ros-hydro-control-msgs, ros-hydro-denso-controller, ros-hydro-vs060-moveit-config
> 競合: ros-hydro-denso-launch
> 説明: denso_launch
> 
> ホームページ: http://wiki.ros.org/denso

**Comment by k-okada** [comment]
thanks for catch, fixed in #42

**Comment by 130s** [comment]
+1
