### ISSUE TITLE
Indigo release and other questions from industry

### ISSUE THREAD

**Issue by 130s** [start-jsk/denso#46]
Following inquiry received offline.

---

Dear sirs,

My name is XXX, and I'm a lecturer with YYYYYYYY where I'm familiar with KUKA robots. I have recently taken up consulting with with a local company who have a Denso VS-6577GM and RC7 controller.

I understand that the current state of the denso packages in ROS does not support the above. However, it would be to my company's benefit to be able to control this robot without having to use Wingcap III or pacscript, and so I would like to explore the possibility of implementing this support. However, as I'm not familiar with Denso (beyond the pacscript capabilities which I have just learnt up over the past few weeks) and ROS, I'd like to ask the following questions from the both of you.
1. The current release of ROS is indigo, and in my distribution (Arch Linux) most packages are already moving there. May I assume that the denso packages in current form are not compatible? And if so, are there plans to do that (git doesn't seem to show much activity in that direction)?
2. Some closed issues reference splitting main.cpp to simplify implementing other controllers, are there plans to do this?
3. Depending on the answers to above, of course, but what can I do at this point to advance support for the robot I have? Any documentation you can point me to for b-cap would be appreciated, in particular.

Thank you, and I apologise for the imposition on your time.

**Comment by 130s** [comment]
> 1 The current release of ROS is indigo, and in my distribution (Arch Linux) most packages are already moving there. May I assume that the denso packages in current form are not compatible? And if so, are there plans to do that (git doesn't seem to show much activity in that direction)?

Indigo release is not planned yet, but it has to happen at some point. I assume this will be in early 2015 when we'll hope to see the full maturity of ROS Indigo (it may already have been mature, but we prefer to following "industry" standard to wait for certain period before moving on to a new platform).

> 2 Some closed issues reference splitting main.cpp to simplify implementing other controllers, are there plans to do this?

Thank you for pointing that out. As [noted in wiki](http://wiki.ros.org/denso#Software_architecture_thoughts) as well, the core components will be replaced with more common controller packages. This change, however, should not change the way the current user interact with the package and the robot (there will only be addtions of new features that are available through the new controllers though).

> 3 Depending on the answers to above, of course, but what can I do at this point to advance support for the robot I have? Any documentation you can point me to for b-cap would be appreciated, in particular.

You're always welcomed to open questions on this issue tracker for specific topics. Also patches (called `pull request` on github as you know) are appreciated.
https://github.com/start-jsk/denso/issues

If you seek a support with guaranteed response timeframe, TORK provides a professional support. Please contact support@opensource-robotics.tokyo.jp for more detail.

Please do not hesitate to reopen the ticket if anything is still unclear.

**Comment by k-okada** [comment]
> 2 Some closed issues reference splitting main.cpp to simplify implementing other controllers, are there plans to do this?

As far as I understand current implementation correctly, you can load and use any ros controller plugin to denso controller. Please try them.
