### ISSUE TITLE
Announce densowave to community

### ISSUE THREAD

**Issue by 130s** [start-jsk/denso#5]
Mentioned via https://github.com/start-jsk/open-source-robotics-consultant/issues/31#issuecomment-29871269

**Comment by 130s** [comment]
@k-okada Minimum left todo in my head:
- [x] Elevator-pitch description. Maybe for open_industrial_controller as well.
- [ ] runtime test (by running `MoveIt!-RViz` simulation. Work in progress #1 )
- [ ] API doc (if anything simplest)

**Comment by 130s** [comment]
how-to-run description half done http://wiki.ros.org/denso_launch#Denso.27s_VS060_on_RViz

**Comment by 130s** [comment]
TODO について，

> runtime test (by running MoveIt!-RViz simulation. Work in progress #1 )
> API doc (if anything simplest)

これはアナウンス後でも良いか．
API doc 作成は[移譲](https://github.com/start-jsk/open_industrial_ros_controllers/issues/13)．

http://wiki.ros.org/densowave に以下最低限を書いたのでアナウンスして良いかということでクローズ．
- iREX 実機の動画 (@garaemon 提供)，RViz の snapshot
- iREX の MoveIt! サンプルコード (コードの説明は書いてませんが)
- コミュニティ連絡先

**Comment by 130s** [comment]
Announcement made to the ML also now posted on wiki http://www.ros.org/news/2013/12/new-package-densowave-manipulator-if-for-industrial-arms.html

**Comment by k-okada** [comment]
Great!!!

If possible, how about ask Tully? to add images and videos embedded in the wiki.

**Comment by garaemon** [comment]
awesome!

2013年12月27日金曜日 Kei Okada notifications@github.com:

> Great!!!
> 
> If possible, how about ask Tully? to add images and videos embedded in the
> wiki.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/start-jsk/densowave/issues/5#issuecomment-31243722
> .

## 

-- ryohei

**Comment by emijah** [comment]
Congratulations!

**Comment by 130s** [comment]
New video posted: [VS060 integrated with vision (xtion)](http://wiki.ros.org/denso?distro=hydro#denso_launch.VS060_integrated_with_vision_.28xtion.29)
