### ISSUE TITLE
URDF file for VS6577-BW*

### ISSUE THREAD

**Issue by Booooooosh** [start-jsk/denso#89]
Is there any URDF for VS6577-BW* model?

**Comment by k-okada** [comment]
Unfortunately, we do not have URDF which is not listed in this repository. We need to find from somewhere.

**Comment by Booooooosh** [comment]
Hi, many thanks for the reply.
But where can I find the URDF for this model? Or do I have to create one?
Many thanks!

**Comment by Booooooosh** [comment]
Hi, just a follow up question. I looked through the urdf file for VS060. Just curious whether is it possible to replace the VS060 URDF with VS6577-BW URDF(I can try building the URDF myself, since I'm not using GAZEBO, it could be simpler), and keep the rest pf the launch file the same?
Will this work? Basically what I mean is that does the denso_ros_controller works for VS6577 also? (Since they are all 6DOF, I assume the controller can do the same thing for VS6577)?

Many thanks!

**Comment by k-okada** [comment]
I think that should work

--
◉ Kei Okada


2017-11-21 13:43 GMT+09:00 Booooooosh <notifications@github.com>:

**Comment by Booooooosh** [comment]
Alright, I’ve done the URDF for the VS6577, will make a try!
Many thanks!


发自我的 iPhone

**Comment by YoshihiroMIYAKOSHI** [comment]
You can use ROSConverter.exe which is included in the latest WINCAPS III.
The ROSConverter is located in the WINCAPS III install media:
$(install media)\Unsupported\Tools\ROSConverter\Bin\ROSConverter.exe

This tool convert WINCAP III project to ROS URDF.

**Comment by Booooooosh** [comment]
Many thx! Though I believe I have an older version of WINCAPS. However, I have built the URDF, and can use it in the MoveIt, next step is to make sure that the controller can connnect to the real robot. By that I mean the vs060 ros controller can also be used for vs6557.

发自我的 iPhone
