### ISSUE TITLE
Shall we use kinetic level or indigo level?

### ISSUE THREAD

**Issue by Booooooosh** [start-jsk/denso#92]
Well, I know I'm using ros-indigo, but just curious whether I can still use the kinetic-devel branch since this branch is recently being maintained and the denso-ros-controller seems to be robot-agnostic. On the contrary, the denso-launch package in the indigo-devel branch seems to be specific to VS060 (However, I am using a VS6577 right now...)

Many thanks for your time!

**Comment by k-okada** [comment]
both could be ok, but yes, kinetic has latest package and that should be
compilable on indigo too.
basically you need vs6577 and vs6577_moviet_consfig instead of vs060 of
that.

--
◉ Kei Okada


2017-11-27 6:11 GMT+09:00 Booooooosh <notifications@github.com>:

**Comment by Booooooosh** [comment]
That works. Many thanks!
