### ISSUE TITLE
Is it possible to open I/O port  using denso package

### ISSUE THREAD

**Issue by Booooooosh** [start-jsk/denso#96]
I want to control an I/O port on fly, is it possible that I can do this using the DENSO ROS package? Or I need to write my own node using the bCap.c?

Many thanks!

**Comment by k-okada** [comment]
currently IO is not implemented, so we need to write by yourself (and send
us PR of it), or you may try https://github.com/DENSORobot/denso_robot_ros,
we'are planning to transit from our code to code re-written by denso team,
they might have IO support.

--
◉ Kei Okada


2017-12-08 4:54 GMT+09:00 Booooooosh <notifications@github.com>:

**Comment by Booooooosh** [comment]
OK, I'll look into that. BTW, the repo posted here, it seems that they are recently committed. Is this a tested package or it's under development now?
Many thanks!
